### PR TITLE
Fix deleteUser

### LINKED ISSUE #20: deleteUserData not working
When a user deletes their profile, deleteUserData is supposed to clear the oauthId -> uid mapping this plugin is keeping. Howerver, that fails since the <name>Id field on the user does not pass a whitelist. This in turn leads to the mapping not being deleted. I will soon push a fix that involves using the whitelist hook.

### PR DESCRIPTION
**Pull request by LudwikJaniuk**
Whitelist filter for user fields needed in deletion. Fix #20.

### CODE REVIEW

**Comment by LudwikJaniuk** [comment]
One thing I realized tho is that, if the user's oauthId record is somehow missing, profile deletion will always fail. This is because I throw that error if it's missing. Do you think that's a good thing or not?

**Comment by julianlam** [comment]
LGTM, but I don't see you passing any errors in this PR?

**Comment by LudwikJaniuk** [comment]
Oh, you're right, I actually didn't commit that. Not sure why. But locally I would callback with an error right here: https://github.com/julianlam/nodebb-plugin-sso-oauth/pull/21/commits/8cfdd45de7e3bdef36775265448c9faed5c9428d#diff-23d0409eda55ae4e1330ef5acbab63f8R255 if the `oAuthIdToDelete` was missing. I didn't like the idea of continuing as usual in that case, but I also don't like the fact that throwing the error cancels the whole user deletion process. What do you think, should I add it back?

**Comment by julianlam** [comment]
Should be fine without error... ~to my knowledge~ (verified now), if you call `db.deleteObjectField` and pass in a field that doesn't exist, or a set that doesn't exist, no error is returned, since the record never existed in the first place.

**Comment by julianlam** [comment]
Appreciate your attention to detail :)

**Pull request merged**
